apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageregistry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageregistryapp
  template:
    metadata:
      labels:
        app: imageregistryapp
    spec:
      serviceAccountName: registrysa
      containers:
        - name: registry  # name used in docker yaml part_5_pi_jms_jib/docker/registry
          image: localhost:5000/registry:latest
          ports:
            - containerPort: 80