version: '3.8'

services:
  clamav_rest_service:
    container_name: clamav_rest_service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # see springboot config: bootstrap-clamav_service-generic.properties
      # passed to supervisord run.conf as "ENV_SPRING_PROFILE"
      - SPRING_PROFILE=clamav_service-generic
      # seems we have to evaluate all properties, otherwise springboot does not recognize them
      - EUREKA_ENABLED=${EUREKA_ENABLED}
      - EUREKA_URI=${EUREKA_URI}
      - CLAMAV_REST_API_PORT=${CLAMAV_REST_API_PORT}
      - CLAMAV_REST_SERVICE_NAME=clamav-rest-servce_${CLAMAV_REST_API_PORT}
    ports:
      - ${CLAMAV_REST_API_PORT}:3316
    networks:
      - network_internal

networks:
  network_internal:
    external:
      name: ${CLAMAV_NETWORK}